### ISSUE TITLE
Can't send email to gmail with sendmail

### ISSUE THREAD

**Issue by AndreaHasani** [tomav/docker-mailserver#1120]
## Context

Sending email to a gmail account from the server. Test done with python sendmail

## Expected Behavior

Sending the message succesfully

## Actual Behavior

I get an RCPT from unknow error.

This server works when I send email from a client to gmail just sending them from the server to a gmail doesn't work. Right now the following works.

client -> gmail (Works)
python sendmail -> domain email (works)
python sendmail -> gmail email (Problem)

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* 3gb
* Mailserver version used: Latest Tag
* Docker version used: Docker version 18.09.0, build 4d60db4
* Environment settings relevant to the config: 
* Any relevant stack traces ("Full trace" preferred):

docker-mailserver latest 20 lines, logs
```
Jan 29 17:25:24 mail postfix/smtpd[29163]: lost connection after RSET from unknown[172.26.0.1]
Jan 29 17:25:24 mail postfix/smtpd[29163]: disconnect from unknown[172.26.0.1] ehlo=1 mail=1 rcpt=0/1 rset=1 commands=3/4
Jan 29 17:25:25 mail postfix/postscreen[14429]: CONNECT from [172.26.0.1]:43776 to [172.26.0.2]:25
Jan 29 17:25:25 mail postfix/postscreen[14429]: PASS OLD [172.26.0.1]:43776
Jan 29 17:25:25 mail postfix/smtpd[29163]: connect from unknown[172.26.0.1]
Jan 29 17:25:25 mail postfix/smtpd[29163]: NOQUEUE: reject: RCPT from unknown[172.26.0.1]: 554 5.7.1 <pasqyra3d@gmail.com>: Relay access denied; from=<localhost> to=<pasqyra3d@gmail.com> proto=ESMTP helo=<[172.28.0.2]>
Jan 29 17:25:25 mail postfix/smtpd[29163]: lost connection after RSET from unknown[172.26.0.1]
Jan 29 17:25:25 mail postfix/smtpd[29163]: disconnect from unknown[172.26.0.1] ehlo=1 mail=1 rcpt=0/1 rset=1 commands=3/4
Jan 29 17:25:27 mail postfix/postscreen[14429]: CONNECT from [172.26.0.1]:43784 to [172.26.0.2]:25
Jan 29 17:25:27 mail postfix/postscreen[14429]: PASS OLD [172.26.0.1]:43784
Jan 29 17:25:27 mail postfix/smtpd[29163]: connect from unknown[172.26.0.1]
Jan 29 17:25:27 mail postfix/smtpd[29163]: NOQUEUE: reject: RCPT from unknown[172.26.0.1]: 554 5.7.1 <pasqyra3d@gmail.com>: Relay access denied; from=<localhost> to=<pasqyra3d@gmail.com> proto=ESMTP helo=<[172.28.0.2]>
Jan 29 17:25:27 mail postfix/smtpd[29163]: lost connection after RSET from unknown[172.26.0.1]
Jan 29 17:25:27 mail postfix/smtpd[29163]: disconnect from unknown[172.26.0.1] ehlo=1 mail=1 rcpt=0/1 rset=1 commands=3/4
Jan 29 17:25:31 mail postfix/postscreen[14429]: CONNECT from [172.26.0.1]:43792 to [172.26.0.2]:25
Jan 29 17:25:31 mail postfix/postscreen[14429]: PASS OLD [172.26.0.1]:43792
Jan 29 17:25:31 mail postfix/smtpd[29163]: connect from unknown[172.26.0.1]
Jan 29 17:25:31 mail postfix/smtpd[29163]: NOQUEUE: reject: RCPT from unknown[172.26.0.1]: 554 5.7.1 <pasqyra3d@gmail.com>: Relay access denied; from=<localhost> to=<pasqyra3d@gmail.com> proto=ESMTP helo=<[172.28.0.2]>
Jan 29 17:25:31 mail postfix/smtpd[29163]: lost connection after RSET from unknown[172.26.0.1]
Jan 29 17:25:31 mail postfix/smtpd[29163]: disconnect from unknown[172.26.0.1] ehlo=1 mail=1 rcpt=0/1 rset=1 commands=3/4
```

Python script function sending the email
```
def sendMessage(subject, message, fromEmail="localhost"):
    msg = MIMEText(message)
    msg['From'] = fromEmail
    msg['To'] = "pasqyra3d@gmail.com"
    msg['Subject'] = subject
    msg['Date'] = formatdate()
    msg['X-Domain'] = "andreahasani.com"
    msg['X-System'] = "python"

    server = smtplib.SMTP('172.17.0.1')
    server.sendmail(fromEmail, 'pasqyra3d@gmail.com', msg.as_string())

```

docker-compose.yml for the script

```
version: '3'
services:
  upwork:
    restart: always
    build: .
    image: upworkapp
    volumes:
      - .:/usr/src/upworkApp

    extra_hosts:
      - "outside:172.17.0.1"

    command: python /usr/src/upworkApp/main.py


```

**Comment by johansmitsnl** [comment]
Change the from localhost to a email address that is known to the server

**Comment by AndreaHasani** [comment]
@johansmitsnl Done. Still same problem. That wouldn't matter because it works fine with localhost when i send it to email@andreahasani.com which is the domain where the server resides.

Here's the log from the python file.

```
Traceback (most recent call last):
  File "/usr/src/upworkApp/main.py", line 26, in <module>
    sendMessage("[Upwork Notifier] Started", "")
  File "/usr/src/upworkApp/main.py", line 23, in sendMessage
    server.sendmail(fromEmail, 'pasqyra3d@gmail.compile', msg.as_string())
  File "/usr/local/lib/python3.6/smtplib.py", line 881, in sendmail
    raise SMTPRecipientsRefused(senderrs)
smtplib.SMTPRecipientsRefused: {'pasqyra3d@gmail.compile': (554, b'5.7.1 <pasqyra3d@gmail.compile>: Relay access denied')}
```

I don't know what relay means

**Comment by johansmitsnl** [comment]
Do you use port 587 for sending the email?

**Comment by AndreaHasani** [comment]
@johansmitsnl Yes. I tried with server.starttls(), same problem. Tried adding the port on the serverip. Same problem.
Maybe this needs some kind of configuration on the email server. I read somewhere that I need to do relay configuration but I don't know what that's used for.

**Comment by AndreaHasani** [comment]
@johansmitsnl I'm sending the email from same server when the mail server is. As I said before it works If I sent it to my domain email. Also I can use email clients to send email without problems. Only in this case is not working.

**Comment by johansmitsnl** [comment]
If you can use other clients to send email to the gmail account then there is an issue with the mail library.
If it sends over 587 as an authenticated user with the correct from email address (same as in your client test) it should work as you tested with the email client.

**Comment by AndreaHasani** [comment]
Yeah, I come to that conclusion too. Thanks for the help
