### ISSUE TITLE
Cannot run the image

### ISSUE THREAD

**Issue by kuba-orlik** [tomav/docker-mailserver#1339]
## Context

I'm setting up docker-mailserver on a fresh debian 10 VPS

## Expected Behavior

`docker-compose up -d` should run the mailserver

## Actual Behavior
Instead, it shows this error:

```
Starting mail ... 

ERROR: for mail  a bytes-like object is required, not 'str'

ERROR: for mail  a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "site-packages/docker/api/client.py", line 261, in _raise_for_status
  File "site-packages/requests/models.py", line 940, in raise_for_status
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.22/containers/e7e475514ebb3277c0a26452f3a5dacdc7fb7f1da06779067ed34644f30ac4bd/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "compose/service.py", line 625, in start_container
  File "compose/container.py", line 241, in start
  File "site-packages/docker/utils/decorators.py", line 19, in wrapped
  File "site-packages/docker/api/container.py", line 1095, in start
  File "site-packages/docker/api/client.py", line 263, in _raise_for_status
  File "site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 500 Server Error: Internal Server Error ("b'driver failed programming external connectivity on endpoint mail (9e39fc656441eeaa83f41b1e4659e47ee3c0e2f530ad9439eee30f9c087541cb): Error starting userland proxy: listen tcp 0.0.0.0:25: bind: address already in use'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 72, in main
  File "compose/cli/main.py", line 128, in perform_command
  File "compose/cli/main.py", line 1107, in up
  File "compose/cli/main.py", line 1103, in up
  File "compose/project.py", line 570, in up
  File "compose/parallel.py", line 112, in parallel_execute
  File "compose/parallel.py", line 210, in producer
  File "compose/project.py", line 556, in do
  File "compose/service.py", line 568, in execute_convergence_plan
  File "compose/service.py", line 510, in _execute_convergence_start
  File "compose/parallel.py", line 112, in parallel_execute
  File "compose/parallel.py", line 210, in producer
  File "compose/service.py", line 508, in <lambda>
  File "compose/service.py", line 620, in start_container_if_stopped
  File "compose/service.py", line 627, in start_container
TypeError: a bytes-like object is required, not 'str'
[11333] Failed to execute script docker-compose
```
## Your Environment

* Amount of RAM available: 1.6G
* Mailserver version used: latest (docker image id: c68cfea45de2)
* Docker version used: Docker version 19.03.5, build 633a0ea838
* Docker-compose version used: docker-compose version 1.25.0, build 0a186604
* Any relevant stack traces ("Full trace" preferred): posted above

**Comment by kuba-orlik** [comment]
Ok, so the problem was casued by the fact that my server had an smtp server already listening on the 25 port I've found using `ss -tulp` that it's `exim4` and disabled it with `systemctl stop exim4 && systemctl disable exim4`
