### ISSUE TITLE
Container command '/bin/sh' not found or does not exist.

### ISSUE THREAD

**Issue by belstgut** [tomav/docker-mailserver#218]
```
% docker-compose up -d mail                                                                                                          :(
Starting mail

ERROR: for mail  b"Container command '/bin/sh' not found or does not exist."
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/compose/cli/main.py", line 58, in main
    command()
  File "/usr/lib/python3.5/site-packages/compose/cli/main.py", line 109, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3.5/site-packages/compose/cli/main.py", line 734, in up
    remove_orphans=remove_orphans)
  File "/usr/lib/python3.5/site-packages/compose/project.py", line 402, in up
    'Encountered errors while bringing up the project.'
compose.project.ProjectError: Encountered errors while bringing up the project.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.7.1', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3.5/site-packages/compose/cli/main.py", line 63, in main
    log.error(e.msg)
AttributeError: 'ProjectError' object has no attribute 'msg'

```

**Comment by belstgut** [comment]
same when trying to build the dockerfile from github directly:

```
% docker build github.com/tomav/docker-mailserver                                                                                    
Sending build context to Docker daemon 622.1 kB
Step 1 : FROM ubuntu:14.04
14.04: Pulling from library/ubuntu
56eb14001ceb: Pull complete 
7ff49c327d83: Pull complete 
6e532f87f96d: Pull complete 
3ce63537e70c: Pull complete 
Digest: sha256:d67ef8e385f1c8b13d8c3e7622dc31b51d07e5623c1d034ebe2acb14a11fb30d
Status: Downloaded newer image for ubuntu:14.04
 ---> 38c759202e30
Step 2 : MAINTAINER Thomas VIAL
 ---> Running in 2387387bd110
 ---> e0e228d97901
Removing intermediate container 2387387bd110
Step 3 : RUN DEBIAN_FRONTEND=noninteractive apt-get update -q --fix-missing &&  apt-get -y upgrade &&   apt-get -y install --no-install-recommends    postfix dovecot-core dovecot-imapd dovecot-pop3d dovecot-sieve dovecot-managesieved gamin amavisd-new spamassassin razor pyzor libsasl2-modules  clamav clamav-daemon libnet-dns-perl libmail-spf-perl bzip2 file gzip p7zip unzip arj rsyslog     opendkim opendkim-tools opendmarc curl fail2ban ed iptables &&      curl -sk http://neuro.debian.net/lists/trusty.de-m.libre > /etc/apt/sources.list.d/neurodebian.sources.list &&  apt-key adv --recv-keys --keyserver hkp://pgp.mit.edu:80 0xA5D32F012649A5A9 &&         apt-get update -q --fix-missing && apt-get -y upgrade fail2ban &&     apt-get autoclean && rm -rf /var/lib/apt/lists/* &&     rm -rf /usr/share/locale/* && rm -rf /usr/share/man/* && rm -rf /usr/share/doc/*
 ---> Running in 0cdb7e23d823
Container command '/bin/sh' not found or does not exist.
```
