### ISSUE TITLE
ELK - field [received_at] doesn't exist

### ISSUE THREAD

**Issue by tomav** [tomav/docker-mailserver#336]
When running fixtures, this error shows:

```
RemoteTransportException[[Set][172.20.0.2:9300][indices:data/read/field_stats[s]]]; nested: IllegalArgumentException[field [received_at] doesn't exist];
Caused by: java.lang.IllegalArgumentException: field [received_at] doesn't exist
    at org.elasticsearch.action.fieldstats.TransportFieldStatsTransportAction.shardOperation(TransportFieldStatsTransportAction.java:166)
    at org.elasticsearch.action.fieldstats.TransportFieldStatsTransportAction.shardOperation(TransportFieldStatsTransportAction.java:54)
    at org.elasticsearch.action.support.broadcast.TransportBroadcastAction$ShardTransportHandler.messageReceived(TransportBroadcastAction.java:282)
    at org.elasticsearch.action.support.broadcast.TransportBroadcastAction$ShardTransportHandler.messageReceived(TransportBroadcastAction.java:278)
    at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:77)
    at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:376)
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by castorinop** [comment]
test create a index with with time-field @timestamp 
apparently not all logs from syslog are RFC-3164 compliant and logstash can't work well. 

https://discuss.elastic.co/t/indices-data-read-field-stats-s-nested-illegalargumentexception-field-timestamp-doesnt-exist/52738/15

**Comment by tomav** [comment]
Seems to work, thanks!
