### ISSUE TITLE
Dockerfile build fails :  pyzor on SourceForge is experiencing connectivity issues

### ISSUE THREAD

**Issue by scottstensland** [tomav/docker-mailserver#729]
for past 24 hours cannot build Dockerfile due to
pyzor download consistently fails as acknowledged by sourceforce ops at

        https://twitter.com/sfnet_ops

"SourceForge is experiencing connectivity issues. We are working with our upstream provider."

Step 38/62 : RUN razor-admin -create && razor-admin -register && pyzor discover
 ---> Running in b1f7d1c17ed2
Register successful.  Identity stored in /var/lib/amavis/.razor/identity-ruiYeoVskC
downloading servers from http://pyzor.sourceforge.net/cgi-bin/inform-servers-0-3-x
Traceback (most recent call last):
  File "/usr/bin/pyzor", line 8, in <module>
    pyzor.client.run()
  File "/usr/lib/python2.7/dist-packages/pyzor/client.py", line 1022, in run
    ExecCall().run()
  File "/usr/lib/python2.7/dist-packages/pyzor/client.py", line 186, in run
    download(config.get('client', 'DiscoverServersURL'), servers_fn)
  File "/usr/lib/python2.7/dist-packages/pyzor/client.py", line 1031, in download
    open(outfile, "wb").write(urllib2.urlopen(url).read())
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1136, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
socket.error: [Errno 104] Connection reset by peer

Am seeing same issue booked previously at  https://github.com/tomav/docker-mailserver/issues/389

Wonder if we can obtain pyzor from more stable location

**Comment by johansmitsnl** [comment]
I guess it is the discover function that was not working
https://github.com/tomav/docker-mailserver/blob/a2efdab5ddf4941756e048b4a5a879983127aaf1/Dockerfile#L147
This is within their software and not familiar if there are mirrors of it?

**Comment by jujes** [comment]
**Same issue here:**

```
Step 28/50 : RUN razor-admin -create &&   razor-admin -register &&   pyzor discover
 ---> Running in be1794fc879f
Register successful.  Identity stored in /var/lib/amavis/.razor/identity-rugJbcH9fB
downloading servers from http://pyzor.sourceforge.net/cgi-bin/inform-servers-0-3-x
Traceback (most recent call last):
  File "/usr/bin/pyzor", line 8, in <module>
    pyzor.client.run()
  File "/usr/lib/python2.7/dist-packages/pyzor/client.py", line 1022, in run
    ExecCall().run()
  File "/usr/lib/python2.7/dist-packages/pyzor/client.py", line 186, in run
    download(config.get('client', 'DiscoverServersURL'), servers_fn)
  File "/usr/lib/python2.7/dist-packages/pyzor/client.py", line 1031, in download
    open(outfile, "wb").write(urllib2.urlopen(url).read())
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 110] Connection timed out>
The command '/bin/sh -c razor-admin -create &&   razor-admin -register &&   pyzor discover' returned a non-zero code: 1
```

**Comment by scottstensland** [comment]
I just booked a ticket directly on the upstream support page

https://sourceforge.net/p/forge/site-support/15649/

**Comment by johansmitsnl** [comment]
@scottstensland any information on your support request?

**Comment by mwlczk** [comment]
pyzor 1.0 (available since Dec 2014(!)) does not have the `discover` command anymore, look here https://github.com/SpamExperts/pyzor/commit/50f2bf5aa47ed863de78c413ff7114f5e54f5a9b

this should be removed from the Dockerfile.
